### ISSUE TITLE
Tags in the device metadata are not set

### ISSUE THREAD

**Issue by shanethehat** [serverdensity/chef-serverdensity#19]
I'm trying to pass some tags in device metadata. The devices are created as expected, but they are not tagged. I'm certain that the tag IDs I'm passing are correct.

This is the role where my config is defined:

    {
      "name": "monitored",
      "description": "Monitored",
      "json_class": "Chef::Role",
      "default_attributes": {
        "serverdensity": {
          "token": "xxxxxxxxxxxxxxx",
          "account": "xxxxxxx.serverdensity.io",
          "device_group": "xxxxxxxx"
        },
        "serverdensity-xxxxxxxx": {
          "tags": [
            "xxxxxxxxxxxx",
            "xxxxxxxxxxxx"
          ]
        }
      },
      "override_attributes": {
      },
      "chef_type": "role",
      "run_list": [
        "recipe[serverdensity-xxx]"
      ],
      "env_run_lists": {
      }
    }

And this is the serverdensity-xxx default recipe:

    include_recipe 'serverdensity'

    serverdensity node.name do
      metadata :tags => node['serverdensity-xxx']['tags']
    end

**Comment by mal** [comment]
Annoyingly there's no example in the v2 API docs that shows what tags look like. What you're doing looks logical, but the docs say "A serialized JSON list with the tag IDs." I'm unsure if that's a mistake or if it's expecting a string value rather than a JSON array.

Do you have a sample API call that does work? I'm not at a work station right now, but I'll take a look when I am.

**Comment by carlosperello** [comment]
@mal , it's a regular JSON array with a list of tag IDs. I just fixed the documentation to clarify it. Thank you for pointing it.

**Comment by mal** [comment]
Ok, so because create/update uses `application/x-www-form-urlencoded`, the correct way to do this is to serialize after all:

```rb
require 'json'

include_recipe 'serverdensity'

serverdensity node.name do
  metadata :tags => JSON.dump(node['serverdensity-xxx']['tags'])
end
```

That will solve your immediate problem. I suspect, however, that due to the way SD data is cached in Chef (to prevent having to check the API to determine if an update is required) it won't recognise when your tags have already been set and will attempt to update your device's metadata on every deploy. This shouldn't have any impact on the operation of your device or SD, but it may mean a slightly longer deploy.

It probably makes sense to alter this behavior and release a new version of the cookbook that handles the `JSON.dump`ing and fixes the caching problem, but at least in the short term you can still have Chef tag your device.

**Comment by mal** [comment]
On a more general note, this is [another case](16) where visible output from the API would have helped as it was responding with:

```json
{"type":"invalid_param","param":"tags","description":"tags is invalid, it should be a valid JSON object."}
```

**Comment by shanethehat** [comment]
Awesome, thanks @mal. This solution gets me working again for now, but I'll leave the issue open as a feature request.

**Comment by shurl** [comment]
We've released v3 of the cookbook, if you still deem this an issue please get in touch.
